Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,10 @@
 name: Cypress Tests
 
   # runs tests every day at 4am
-#on:
- # schedule:
-  #  - cron: '*/5 * * * *'
-on: [ push ]
+on:
+  schedule:
+    - cron: '*/5 * * * *'
+#on: [ push ]
 
 
 permissions: write-all
@@ -495,20 +495,20 @@ jobs:
         shell: bash
 
       - uses: actions/checkout@v2
-        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '3')
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
 
       - uses: actions/setup-node@v3
-        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '3')
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
 
       - run: npm i
-        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '3')
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
 
       - uses: nick-invision/retry@v2
         with:
           timeout_minutes: 10
           max_attempts: 3
           command: npm run e2e-test17.0
-        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '3')
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
 
       - name: Deploy report to temp-reports branch
         if: always()
@@ -523,7 +523,6 @@ jobs:
 
   Run-Cypress-Test17-1:
     name: Cypress Test 17.1
-    if: success() || failure()
     runs-on: ubuntu-latest
     timeout-minutes: 40
     needs: [ Run-Cypress-Test22 ]
@@ -531,14 +530,26 @@ jobs:
       image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
       options: --user 1001
     steps:
+      - name: Get current date
+        id: get-date
+        run: echo "date=$(date +'%u')" >> $GITHUB_OUTPUT
+        shell: bash
+
       - uses: actions/checkout@v2
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
       - uses: actions/setup-node@v3
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
       - run: npm i
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
       - uses: nick-invision/retry@v2
         with:
           timeout_minutes: 10
           max_attempts: 3
           command: npm run e2e-test17.1
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
 
       - name: Deploy report to temp-reports branch
         if: always()
@@ -552,7 +563,7 @@ jobs:
 
   Run-Cypress-Test17-2:
     name: Cypress Test 17.2
-    if: success() || failure()
+   # if: success() || failure()
     runs-on: ubuntu-latest
     timeout-minutes: 40
     needs: [ Run-Cypress-Test1 ]
@@ -560,14 +571,27 @@ jobs:
       image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
       options: --user 1001
     steps:
+      - name: Get current date
+        id: get-date
+        run: echo "date=$(date +'%u')" >> $GITHUB_OUTPUT
+        shell: bash
+
       - uses: actions/checkout@v2
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
       - uses: actions/setup-node@v3
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
       - run: npm i
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
       - uses: nick-invision/retry@v2
         with:
           timeout_minutes: 10
           max_attempts: 3
           command: npm run e2e-test17.2
+        if: (github.event_name == 'schedule' && steps.get-date.outputs.date == '4')
+
 
       - name: Deploy report to temp-reports branch
         if: always()
