Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,17 +13,23 @@ jobs:
     if: success() || failure()
     runs-on: ubuntu-latest
     timeout-minutes: 120
+    continue-on-error: true
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v3
       - run: npm i
       - run: npm run clearGmail
-      - run: npm run e2e-tests-1-10-13-14
-      - continue-on-error: true # this allows the workflow to continue even if tests fail
-      - if: failure() && ${{ contains(github.job.status_message, 'ECONNRESET') }}
-      - run: npm run test
+      - name: Run Cypress Test
+        run: npm run e2e-tests-1-10-13-14 || echo "Cypress failed with error code $?"
+        shell: bash
+        env:
+          NODE_OPTIONS: --max-old-space-size=4096
+      - name: Rerun Cypress Test if ECONNRESET
+        if: ${{ failure() && contains(github.job.output, 'ECONNRESET') }}
+        run: npm run e2e-tests-1-10-13-14
+  
 
-        
+
   Run-Clear-Gmail:
     name: Clear Gmail
     if: success() || failure()
